version: 2
jobs:
  build:
    docker:
      - image: circleci/node:fermium-bullseye-browsers-legacy
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm posttest
